name: dblabs_api_repo
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.3


dependencies:
  dblabs_api:
    path: ../dblabs-api/dart
  grpc: ^3.2.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
